name = "portfolio-metrics-api"
main = "src/index.ts"
compatibility_date = "2026-03-15"
account_id = "4bfdace13a8f558f066ea6e93e3d41d8"
workers_dev = true

[vars]
ALLOWED_ORIGIN = "*"

[[kv_namespaces]]
binding = "METRICS"
id = "fead888804e44d66b861ef936027f2ae"
