CREATE TABLE IF NOT EXISTS post_metrics (
  post_id VARCHAR(255) PRIMARY KEY,
  views INT NOT NULL DEFAULT 0,
  likes INT NOT NULL DEFAULT 0,
  shares INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS post_views (
  post_id VARCHAR(255) NOT NULL,
  visitor_id VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (post_id, visitor_id)
);

CREATE TABLE IF NOT EXISTS post_likes (
  post_id VARCHAR(255) NOT NULL,
  visitor_id VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (post_id, visitor_id)
);
